-- Auto-generated by matugen, do not edit manually
return {
	base00 = "#1a110f",
	base01 = "#231917",
	base02 = "#271d1b",
	base03 = "#a08c88",
	base04 = "#534340",
	base05 = "#f1dfdb",
	base06 = "#d8c2bd",
	base07 = "#3d3230",
	base08 = "#ffb4ab",
	base09 = "#dbc58c",
	base0A = "#e7bdb3",
	base0B = "#f8e1a6",
	base0C = "#ffdad2",
	base0D = "#ffb4a3",
	base0E = "#dbc58c",
	base0F = "#93000a",
}
