-- Auto-generated by matugen, do not edit manually
return {
	base00 = "#111318",
	base01 = "#1a1b20",
	base02 = "#1e1f25",
	base03 = "#8e9099",
	base04 = "#44474f",
	base05 = "#e2e2e9",
	base06 = "#c4c6d0",
	base07 = "#33353a",
	base08 = "#ffb4ab",
	base09 = "#debcdf",
	base0A = "#bfc6dc",
	base0B = "#fbd7fc",
	base0C = "#d8e2ff",
	base0D = "#adc6ff",
	base0E = "#debcdf",
	base0F = "#93000a",
}
