background            #1a110f

color0                #534340
color1                #ffb4ab
color2                #dbc58c
color3                #e7bdb3
color4                #ffb4a3
color5                #544519
color6                #dbc58c
color7                #f1dfdb
color8                #534340
color9                #ffdad6
color10               #3c2f04
color11               #442a23
color12               #ffdad2
color13               #f8e1a6
color14               #ffdad2
color15               #d8c2bd

color232              #f1dfdb

cursor                #f1dfdb

foreground            #ffffff

selection_background  #ffdad2
selection_foreground  #5d3f39

# Override obscure colors for starship prompt (these are greys at the end)
color255              #ffb4a3
color254              #723426
color253              #e7bdb3
color252              #5d3f39
color251              #dbc58c
color250              #544519
color249              #ffb4ab
color248              #93000a

color232              #561f12
color233              #ffdad2
color234              #442a23
color235              #ffdad2
color236              #3c2f04
color237              #f8e1a6
color238              #690005
color239              #ffdad6

color244              #a08c88
color245              #534340
