background            #1a110f

color0                #534340
color1                #ffb4ab
color2                #dbc48c
color3                #e7bdb4
color4                #ffb4a4
color5                #544519
color6                #dbc48c
color7                #f1dfdb
color8                #534340
color9                #ffdad6
color10               #3c2f04
color11               #442a24
color12               #561f13
color13               #f8e0a6
color14               #ffdad3
color15               #d8c2bd

color232              #f1dfdb

cursor                #f1dfdb

foreground            #ffffff

selection_background  #ffdad3
selection_foreground  #5d3f39

# Override obscure colors for starship prompt (these are greys at the end)
color255              #ffb4a4
color254              #733427
color253              #e7bdb4
color252              #5d3f39
color251              #dbc48c
color250              #544519
color249              #ffb4ab
color248              #93000a

color232              #561f13
color233              #ffdad3
color234              #442a24
color235              #ffdad3
color236              #3c2f04
color237              #f8e0a6
color238              #690005
color239              #ffdad6

color244              #a08c88
color245              #534340
