background            #111318

color0                #44474f
color1                #ffb4ab
color2                #debcdf
color3                #bfc6dc
color4                #adc6ff
color5                #583e5b
color6                #debcdf
color7                #e2e2e9
color8                #44474f
color9                #ffdad6
color10               #402843
color11               #293041
color12               #102f60
color13               #fbd7fc
color14               #d8e2ff
color15               #c4c6d0

color232              #e2e2e9

cursor                #e2e2e9

foreground            #ffffff

selection_background  #dbe2f9
selection_foreground  #3f4759

# Override obscure colors for starship prompt (these are greys at the end)
color255              #adc6ff
color254              #2b4678
color253              #bfc6dc
color252              #3f4759
color251              #debcdf
color250              #583e5b
color249              #ffb4ab
color248              #93000a

color232              #102f60
color233              #d8e2ff
color234              #293041
color235              #dbe2f9
color236              #402843
color237              #fbd7fc
color238              #690005
color239              #ffdad6

color244              #8e9099
color245              #44474f
