# Configuração do Touchpad (Lenovo IdeaPad)
device {
    name = msft0001:01-04f3:31ad-touchpad

    # 1. Botão Direito Físico
    clickfinger_behavior = false
    tap-to-click = true

    # 2. Ativar Scroll na Borda Direita
    # Valores possíveis: "2fg" (dois dedos), "edge" (borda), "on_button_down", "none"
    scroll_method = edge
    sensitivity = +0.6
    disable_while_typing = false
}
