[config]
reload_apps = true
set_wallpaper = false
scheme_type = "scheme-expressive"
mode = "dark"

[templates.quickshell]
input_path = '~/.config/quickshell/theme/Theme.qml.template'
output_path = '~/.config/quickshell/theme/Theme.qml'


[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk3-override.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk4-override.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qt6ct.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.kvantum_svg]
input_path = '~/.config/matugen/templates/kvantum.svg'
output_path = '~/.config/Kvantum/catppuccin-mocha-sapphire/catppuccin-mocha-sapphire.svg'

[templates.rasi]
input_path = '~/.config/matugen/templates/rounded-nord-dark-larke.rasi'
output_path = '~/.config/rofi/rounded-nord-dark-larke.rasi'


[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-theme.conf'
output_path = '~/.config/hypr/hyprland/theme.conf'


[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock-theme.conf'
output_path = '~/.config/hypr/hyprlock.conf'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-theme.conf'
output_path = '~/.config/kitty/kitty-theme.conf'

[templates.neovim]
input_path = '~/.config/matugen/templates/neovim.lua'
output_path = '~/.config/nvim/lua/matugen_colors.lua'

