# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

exec-once = hyprpm reload

#GameWorkspace
source=GameWorkspace/include.conf

#My custom rules
# 1. Environment Variables & Monitor Setup
source = ~/.config/hypr/hyprland/env.conf
source = ~/.config/hypr/hyprland/monitor.conf
source = ~/.config/hypr/hyprland/permissions.conf

# 2. Core Appearance & Behavior
source = ~/.config/hypr/hyprland/general.conf
source = ~/.config/hypr/hyprland/rules.conf
source = ~/.config/hypr/hyprland/looks.conf

# 3. Input & Keybindings
source = ~/.config/hypr/hyprland/keybinds.conf

# 4. Startup Applications
source = ~/.config/hypr/hyprland/execs.conf

# 5. Special Workspaces Config
source = ~/.config/hypr/hyprland/specialWorkspaces.conf

# 6. Machine Specific Settings
source = ~/.config/hypr/custom/Desktop.conf



