##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Example: 90% opacity for ALL windows
#windowrulev2 = opacity 0.90 0.90,class:^(.*)$

# Example: Make only the terminal (Kitty) transparent
#windowrulev2 = opacity 1 0.,class:^(kitty)$
#windowrulev2 = opacity 0.95 0.9,class:^(org.kde.dolphin)$


#windowrule = match:xwayland true, tile on

windowrule = match:title ^(Picture-in-Picture)$, float on
windowrule = match:title ^(Picture-in-Picture)$, pin on
windowrule = match:title ^(Picture-in-Picture)$, size 772 432

windowrule = match:class ^(hyprland-share-picker)$, pin on
windowrule = match:class ^(hyprland-share-picker)$, stay_focused on
windowrule = match:class ^(hyprland-share-picker)$, focus_on_activate on

windowrule = match:title ^(Fcitx5 Input Window)$, match:class ^(fcitxfcit), float on
windowrule = match:title ^(Fcitx5 Input Window)$, match:class ^(fcitxfcit), pin on


windowrule = match:class ^(steam)$, float on
windowrule = match:title ^(Steam)$, match:class ^(steam)$, tile on

windowrule = match:class ^(krita)$, float on
windowrule = match:title ^(Krita)$, match:class ^(krita)$, tile on

windowrule = match:title ^(Vortex)$, match:class ^(steam_app_default)$,tile on
windowrule = match:title ^(Vortex)$, match:class ^(vortex.exe)$,tile on


windowrule = match:title ^(Vtube Studio), match:class ^(steam_app_1325860), render_unfocused on

windowrule = match:class ^(discord), render_unfocused on


windowrule = match:class ^(krita)$, float on


windowrule = match:class ^(com-cburch-logisim-Main)$, float on

windowrule = match:class ^(xdg-desktop-portal-gtk)$, float on

# BLUR
windowrule =  no_blur on, match:class .*
windowrule =  no_blur off, match:class ^(kitty)
windowrule =  no_blur off, match:class ^(btop)



windowrule = match:initial_class ^(Quartus)$, match:initial_title ^(Quartus II 32-bit)$, float on
