##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Example: 90% opacity for ALL windows
#windowrulev2 = opacity 0.90 0.90,class:^(.*)$

# Example: Make only the terminal (Kitty) transparent
#windowrulev2 = opacity 1 0.,class:^(kitty)$
#windowrulev2 = opacity 0.95 0.9,class:^(org.kde.dolphin)$


windowrule = match:title ^(Picture-in-Picture)$, float on
windowrule = match:title ^(Picture-in-Picture)$, pin on
windowrule = match:title ^(Picture-in-Picture)$, size 772 432

windowrule = match:class ^(hyprland-share-picker)$, pin on


windowrule = match:title ^(Steam Settings)$, match:class ^(steam)$,float on
windowrule = match:title ^(Friends List)$, match:class ^(steam)$,float on
windowrule = match:title ^()$, match:class ^(steam)$,float on

windowrule = match:title ^(Vortex)$, match:class ^(steam_app_default)$,tile on
windowrule = match:title ^(Vortex)$, match:class ^(vortex.exe)$,tile on


windowrule = match:title ^(Vtube Studio), match:class ^(steam_app_1325860), render_unfocused on
