# --- My Special Workspace Window Rules ---
windowrule = workspace special:Whatsapp, match:class ^(com.rtosta.zapzap)$
workspace = special:Whatsapp, on-created-empty: flatpak run com.rtosta.zapzap
windowrule = workspace special:Whatsapp, match:class ^(org.telegram.desktop)$

windowrule = workspace special:discord, match:class ^($discord)
windowrule = workspace special:discord, match:initial_class ^(discord)$
windowrule = workspace special:discord, match:initial_title ^(Discord)$
workspace = special:discord, on-created-empty: flatpak run com.discordapp.Discord

windowrule = match:class ^([sS]potify)$, workspace special:spotify
workspace = special:spotify, on-created-empty: spotify
