# --- My Special Workspace Window Rules ---
windowrule = workspace special:Whatsapp, match:class ^(ZapZap)$
workspace = special:Whatsapp, on-created-empty: zapzap
windowrule = workspace special:Whatsapp, match:class ^(org.telegram.desktop)$

windowrule = workspace special:discord, match:class ^(vesktop)
windowrule = workspace special:discord, match:initial_class ^(vesktop)$
windowrule = workspace special:discord, match:initial_title ^(Discord)$
workspace = special:discord, on-created-empty: vesktop

windowrule = match:class ^([sS]potify)$, workspace special:spotify
workspace = special:spotify, on-created-empty: spotify
