-- ~/.config/matugen/templates/hyprland-theme.lua
-- AUTO-GENERATED BY MATUGEN. DO NOT EDIT DIRECTLY.

hl.config({
  general = {
    col = {
      active_border = {
        colors = { "rgba(ffb4a3ee)", "rgba(dbc58cee)" },
        angle = 45
      },
      inactive_border = "rgba(595959aa)"
    }
  }
})
