-- ~/.config/matugen/templates/hyprland-theme.lua
-- AUTO-GENERATED BY MATUGEN. DO NOT EDIT DIRECTLY.

hl.config({
	general = {
		col = {
			active_border = {
				colors = { "rgba(00000000)", "rgba(00000000)" },
				angle = 45,
			},
			--inactive_border = "rgba(595959aa)"
			inactive_border = "rgba(00000000)",
		},
	},
})
