-- ~/.config/matugen/templates/hyprland-theme.lua
-- AUTO-GENERATED BY MATUGEN. DO NOT EDIT DIRECTLY.

hl.config({
  general = {
    col = {
      active_border = {
        colors = { "rgba(adc6ffee)", "rgba(debcdfee)" },
        angle = 45
      },
      inactive_border = "rgba(595959aa)"
    }
  }
})
