general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

background {
    monitor =
    path = ~/.config/quickshell/assets/wallpaper
    
    # Blur options
    blur_passes = 1
    blur_size = 1
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    dots_size = 0.4
    dots_spacing = 0.15 
    dots_center = true
    dots_rounding = -1 
    
    # Outer Ring: Primary Color with 'ee' alpha (transparency)
    outer_color = rgba({{colors.primary.default.hex_stripped}}ee)
    
    # Inner Background: Surface Color (Solid)
    inner_color = rgba({{colors.surface.default.hex_stripped}}ff)
    
    # Text Color: On Surface (Solid)
    font_color = rgba({{colors.on_surface.default.hex_stripped}}ff)
    
    fade_on_empty = true
    fade_timeout = 1000 
    placeholder_text = <i>Input Password...</i> 
    hide_input = false
    rounding = -1 
    
    # Check Color: Tertiary (Solid)
    check_color = rgba({{colors.tertiary.default.hex_stripped}}ff)
    
    # Fail Color: Error (Solid)
    fail_color = rgba({{colors.error.default.hex_stripped}}ff)
    
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> 
    fail_transition = 300 
    
    position = 0, 50
    halign = center
    valign = bottom
}

label {
    monitor =
    # Clock
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    
    # Clock Color: On Surface (Solid)
    color = rgba({{colors.on_surface.default.hex_stripped}}ff)
    
    font_size = 100
    font_family = Noto Sans
    position = 0, 80
    halign = center
    valign = center
}


label {
    monitor =
    text = 󰜉
        
    color = rgba({{colors.on_surface.default.hex_stripped}}ff)
    
    font_size = 40
    font_family = JetBrainsMono Nerd Font Propo
    position = -39, 23
    halign = right
    valign = bottom
}

shape {
    monitor =
    size = 60, 60
    color = rgba({{colors.surface.default.hex_stripped}}ff)
    rounding = -1 # circle
    border_size = 4
    border_color = rgba({{colors.primary.default.hex_stripped}}ee)

    position = -23, 21
    halign = right
    valign = bottom

    onclick = systemctl reboot
}


label {
    monitor =
    text = 󰐥
    
    color = rgba({{colors.on_surface.default.hex_stripped}}ff)
    
    font_size = 40
    font_family = JetBrainsMono Nerd Font Propo
    position = -129, 20
    halign = right
    valign = bottom
}

shape {
    monitor =
    size = 60, 60
    color = rgba({{colors.surface.default.hex_stripped}}ff)
    rounding = -1 # circle
    border_size = 4
    border_color = rgba({{colors.primary.default.hex_stripped}}ee)

    position = -114, 21
    halign = right
    valign = bottom

    onclick = systemctl poweroff
}
