-- ~/.config/matugen/templates/hyprland-theme.lua
-- AUTO-GENERATED BY MATUGEN. DO NOT EDIT DIRECTLY.

hl.config({
  general = {
    col = {
      active_border = {
        colors = { "rgba({{colors.primary.default.hex_stripped}}ee)", "rgba({{colors.tertiary.default.hex_stripped}}ee)" },
        angle = 45
      },
      inactive_border = "rgba(595959aa)"
    }
  }
})
