background            {{colors.surface.default.hex}}

color0                {{colors.surface_variant.default.hex}}
color1                {{colors.error.default.hex}}
color2                {{colors.tertiary.default.hex}}
color3                {{colors.secondary.default.hex}}
color4                {{colors.primary.default.hex}}
color5                {{colors.tertiary_container.default.hex}}
color6                {{colors.tertiary.default.hex}}
color7                {{colors.on_surface.default.hex}}
color8                {{colors.surface_variant.default.hex}}
color9                {{colors.on_error_container.default.hex}}
color10               {{colors.on_tertiary.default.hex}}
color11               {{colors.on_secondary.default.hex}}
color12               {{colors.on_primary.default.hex}}
color13               {{colors.on_tertiary_container.default.hex}}
color14               {{colors.on_primary_container.default.hex}}
color15               {{colors.on_surface_variant.default.hex}}

color232              {{colors.on_surface.default.hex}}

cursor                {{colors.on_surface.default.hex}}

foreground            #ffffff

selection_background  {{colors.on_secondary_container.default.hex}}
selection_foreground  {{colors.secondary_container.default.hex}}

# Override obscure colors for starship prompt (these are greys at the end)
color255              {{colors.primary.default.hex}}
color254              {{colors.primary_container.default.hex}}
color253              {{colors.secondary.default.hex}}
color252              {{colors.secondary_container.default.hex}}
color251              {{colors.tertiary.default.hex}}
color250              {{colors.tertiary_container.default.hex}}
color249              {{colors.error.default.hex}}
color248              {{colors.error_container.default.hex}}

color232              {{colors.on_primary.default.hex}}
color233              {{colors.on_primary_container.default.hex}}
color234              {{colors.on_secondary.default.hex}}
color235              {{colors.on_secondary_container.default.hex}}
color236              {{colors.on_tertiary.default.hex}}
color237              {{colors.on_tertiary_container.default.hex}}
color238              {{colors.on_error.default.hex}}
color239              {{colors.on_error_container.default.hex}}

color244              {{colors.outline.default.hex}}
color245              {{colors.outline_variant.default.hex}}
