-- Auto-generated by matugen, do not edit manually
return {
	base00 = "#{{colors.surface.default.hex_stripped}}",
	base01 = "#{{colors.surface_container_low.default.hex_stripped}}",
	base02 = "#{{colors.surface_container.default.hex_stripped}}",
	base03 = "#{{colors.outline.default.hex_stripped}}",
	base04 = "#{{colors.outline_variant.default.hex_stripped}}",
	base05 = "#{{colors.on_surface.default.hex_stripped}}",
	base06 = "#{{colors.on_surface_variant.default.hex_stripped}}",
	base07 = "#{{colors.surface_container_highest.default.hex_stripped}}",
	base08 = "#{{colors.error.default.hex_stripped}}",
	base09 = "#{{colors.tertiary.default.hex_stripped}}",
	base0A = "#{{colors.secondary.default.hex_stripped}}",
	base0B = "#{{colors.tertiary_fixed.default.hex_stripped}}",
	base0C = "#{{colors.primary_fixed.default.hex_stripped}}",
	base0D = "#{{colors.primary.default.hex_stripped}}",
	base0E = "#{{colors.tertiary.default.hex_stripped}}",
	base0F = "#{{colors.error_container.default.hex_stripped}}",
}
