#Edit your configs here

#Folders
$GameWorkspace = $HOME/.config/hypr/GameWorkspace
$scripts = $GameWorkspace/scripts

#Main Monitor
#This will define in which screen the games will open
$main_monitor = DP-3


# Forces the main Steam client window to tile.
windowrulev2 = tile, class:^(steam)$, title:^(Steam)$

#Whether to apply blur to transparent windows
$blur = yes

decoration {
    #Default blur
    blur {
        #enabled = yes #Blur is handled as a variable, so change $blur to enable/disable
        size = 5
        passes = 2
        ignore_opacity = false

        noise = 0.08
        contrast = 1.5
        brightness = 0.8

        xray = false
        new_optimizations = true
    }
}

