# Force the 'special:games' workspace to always open on Main Monitor
workspace = special:games, monitor:$main_monitor, default:true


decoration {
    #inactive_opacity = 0.9

    #active_opacity = 0.9


    #Default blur
    blur {
        enabled = $blur
        size = 5
        passes = 2
        ignore_opacity = false

        noise = 0.08
        contrast = 1.5
        brightness = 0.8

        xray = false
        new_optimizations = true
    }
}





