# SUPER + F (Toggle Maximize / Float)
unbind = SUPER, F
bind = SUPER, F, fullscreen, 1

# SUPER + SHIFT + F (Toggle Fullscreen)
unbind = SUPER_SHIFT, F
bind = SUPER_SHIFT, F, fullscreen, 0

# SUPER + G  (Games)
unbind = SUPER, G
bind = SUPER, G, exec, $scripts/gametoggle.sh $main_monitor
# SUPER + SHIFT + G (Move to Games & Add to List)
# Moves the focused window and, if it's a new native game,
# adds it to game-list.json and regenerates the rules.
bind = SUPER + ALT, G, exec, $scripts/add-and-move-game.sh

# Killclose
unbind = SUPER, Q
bind = SUPER, Q, exec, $scripts/close-window.sh
